language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
env:
  - DJANGO="Django==2.2.*"
  - DJANGO="Django==3.0.*"
  - DJANGO="Django==3.1.*"
  - DJANGO="Django==3.2.*"
install:
  - pip install -q $DJANGO
  - pip install -r requirements/base.txt
  - pip install -r requirements/test.txt
  - pip install coveralls
script:
   - PYTHONPATH=".:tests:$PYTHONPATH"  tests/manage.py makemigrations --noinput
   - PYTHONPATH=".:tests:$PYTHONPATH"  tests/manage.py migrate --noinput
   - PYTHONPATH=".:tests:$PYTHONPATH" python -Wall -m coverage run --omit='setup.py' --source=. tests/manage.py test core --settings=
#   - if python -c 'import sys; sys.exit(1 - (sys.version_info >= (3, 6)))'; then isort --check-only magic_notifier tests; fi
after_success:
  - coveralls
