# Generated by Django 3.2.15 on 2023-07-11 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('current_channel', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
                ('type', models.CharField(max_length=30)),
                ('sub_type', models.CharField(blank=True, max_length=30, null=True)),
                ('link', models.CharField(max_length=255, verbose_name='The link associated')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications')),
                ('actions', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('read', models.DateTimeField(blank=True, null=True)),
                ('sent', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magic_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
